### ISSUE TITLE
[Meta] Will nim be quantum?

### ISSUE THREAD

**Issue by nandgator** [nim-lang/needed-libraries#115]
Recently I was going through the [qiskit](https://github.com/Qiskit/qiskit). I was wondering if `nim` can be interfaced with quantum programming. `nim` having so many plus point in performance & being cross platform, it would be great to have a `nimqis` (just kidding :) library that interacts with the quantum world.

> PS: The only library if found connecting `nim` & `quantum` was [`qex`]() but I didn't quiet understand it's purpose. The README begins with how's not why's of the repository.

**Comment by mratsim** [comment]
QEX is a framework for High Energy Physics computation, see presentation at CERN https://indico.cern.ch/event/432527/contributions/1072091/attachments/1320716/1980489/talk_jin_nim_qex.pdf

If there is a C compiler for quantum computers sure. If LLVM supports them, we can probably do it. Otherwise no.

Also I don't expect the first quantum computers to be usable less than 10 years from now which is almost the lifetime of Nim so far.

Closing. The need seems a very long stretch and if this sparks someone interest this should be in the forum first given the super narrow niche.
